# .dockstore.yml for Xena
version: 1.1
service:
  type: docker-compose
  name: UCSC Xena Browser
  author: UCSC Genomics Institute
  description: |
    The UCSC Xena browser is an exploration tool for public and private,
    multi-omic and clinical/phenotype data.
    It is recommended that you configure a reverse proxy to handle HTTPS
  files:
     - docker-compose.yml 
     - README.md
     - stand_up.sh
     - load.sh
     - port.sh
     - stop.sh

  scripts:
    # The next 5 scripts are always executed in the order listed here.
    presprovision: # Before any provisioning
    prestart: # After provisioning, before starting the service
    start: stand_up.sh # Starts the service
    poststart: # After the service has started
    postprovision: load.sh # After the service has started. For multiple provisionings, e.g., the next day

    port: port.sh # Returns the port the service is exposing.
    healthcheck: # Returns
    stop: stop.sh # Stops the service

  # Parameters are passed as environment variables to all of the above scripts. As such, their names need to be valid environment variable names.
  # The exception is parameters of type dataset and dataset[] -- those parameters are provisioned.
  parameters:
    httpPort:
        default: "7222"
        description: The host's HTTP port.
    httpsPort:
        default: "7223"
        description: The host's HTTPS port
    dataset:
        type: dataset[]
        files:
            data:
                description: Data for Xena in TSV format
                targetDirectory: xena/files
            metadata:
                description: The metadata, in JSON format, that corresponds to the data
                targetDirectory: xena/files
