# .dockstore.yml for Xena
# https://github.com/Ldcabansay/xenahub
version: 1.1
service:
  type: docker-compose
  name: UCSC Xena Browser
  author: UCSC Genomics Institute
  description: |
    The UCSC Xena browser is an exploration tool for public and private,
    multi-omic and clinical/phenotype data.
    It is recommended that you configure a reverse proxy to handle HTTPS
  files:
     - docker-compose.yml 
     - README.md
     - stand_up.sh
     - load.sh
     - port.sh
     - stop.sh

  # The following section has scripts that will be invoked
  # in a particular order. The steps with `provision` in their name
  # will only be executed once.
  scripts:
    presprovision:
    prestart:
    start: stand_up.sh
    poststart:
    postprovision: load.sh

    port: port.sh
    healthcheck:
    stop: stop.sh
    # END OPTIONAL section

  parameters:
    description:
        description: An overall description of the parameters
    httpPort:
        default: "7222"
        description: The host's HTTP port.
    httpsPort:
        default: "7223"
        description: The host's HTTPS port
    dataset:
        type: dataset[]
        files:
            data:
                description: Data for Xena in TSV format
                targetDirectory: xena/files
            metadata:
                description: The metadata, in JSON format, that corresponds to the data
                targetDirectory: xena/files
